name: Build Windows
permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-2025
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: >-
            git
            mingw-w64-ucrt-x86_64-boost
            mingw-w64-ucrt-x86_64-cmake
            mingw-w64-ucrt-x86_64-cppwinrt
            mingw-w64-ucrt-x86_64-curl-winssl
            mingw-w64-ucrt-x86_64-miniupnpc
            mingw-w64-ucrt-x86_64-onevpl
            mingw-w64-ucrt-x86_64-openssl
            mingw-w64-ucrt-x86_64-opus
            mingw-w64-ucrt-x86_64-toolchain
            mingw-w64-ucrt-x86_64-MinHook
            mingw-w64-ucrt-x86_64-nodejs
            mingw-w64-ucrt-x86_64-nsis

      - name: Build
        run: |
          mkdir -p build
          cmake -B build -G Ninja -S . \
            -DCMAKE_BUILD_TYPE=Release \
            -DSUNSHINE_ENABLE_CUDA=OFF \
            -DBUILD_DOCS=OFF
          ninja -C build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sunshine-windows
          path: |
            D:/a/Sunshine/Sunshine/build/sunshine.exe
            D:/a/Sunshine/Sunshine/build/*.dll
